# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 実践データサイエンス
author: ""
logo: logo.png

exclude_patterns: [_build, README.md, .DS_Store, org_src]
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering : true
  extra_footer : "" 
  extra_footer: |
    © Copyright 2020-2023 by 吉田 聡太 (Sota Yoshida). 本コンテンツは<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0 ライセンス</a>の下に提供されています。 <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="クリエイティブ・コモンズ・ライセンス" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" /></a>　ただし、資料中のコードセル部分は<a rel="license" href="https://opensource.org/licenses/MIT">MITライセンス</a>の下に提供されています。

launch_buttons:
  binderhub_url: ""  
  colab_url : "https://colab.research.google.com" 

repository:
  url: https://github.com/SotaYoshida/Lecture_DataScience  # Online location of your book
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: "main"  # Which branch of the repository should be used when creating links (optional)

sphinx:
  config:
    html_show_copyright: false
    bibtex_reference_style: author_year